/**
 * Carrying an invite code across the sign-in round trip.
 *
 * Someone tapping an invite link is usually signed out, so they get bounced to
 * /login, wait for an email, and come back through a link in that email. Query
 * parameters don't survive that, so the code is parked in a short-lived cookie
 * instead and picked up once they land on /onboarding.
 */

export const INVITE_COOKIE = "fh_invite";

/** Long enough to receive an email and come back; short enough to go stale. */
export const INVITE_COOKIE_MAX_AGE = 60 * 60; // 1 hour

/** Invite codes are 8 hex characters, as generated by the families table. */
const INVITE_CODE_RE = /^[0-9a-f]{8}$/i;

export function normaliseInviteCode(raw: string | undefined | null): string | null {
  if (!raw) return null;
  const trimmed = raw.trim().toUpperCase();
  return INVITE_CODE_RE.test(trimmed) ? trimmed : null;
}

/** The shareable link for an invite code. */
export function inviteUrl(origin: string, code: string): string {
  return `${origin.replace(/\/$/, "")}/join/${code}`;
}
